### ISSUE TITLE
`dist/PKCE.d.ts` is missing

### ISSUE THREAD

**Issue by freder** [bpedroza/js-pkce#10]
`npm run build` generates the file, but it doesn't make it into the npm package:

![image](https://user-images.githubusercontent.com/724844/119818232-3cb6b480-beef-11eb-90d7-df25b87d31a3.png)

**Comment by bpedroza** [comment]
I'll look into this. Thanks for opening the issue.

**Comment by bpedroza** [comment]
Version 1.1.2 should be up with this fix.
