### ISSUE TITLE
not getting email data from requested scopes

### ISSUE THREAD

**Issue by shiv0808** [bpedroza/js-pkce#17]
Hi, i am trying to obtain the access token from the ping federated Server, and also i am successfully able to get it(thanks to js-pkce).The only concern is while im trying to decode the access token over JWT.io , i am getting payload data as follows:
**{
  "scope": "openid profile address email phone",
  "client_id": "Reg1ABCD",
  "standardATM": "90fSGwCxckjnKH473",
  "iss": "https://something.abc.com",
  "acr": "MS-AD-Kerberos",
  "sub": "someting123",
  "msid": "someting123",
  "exp": 1645704086
}**
I am expecting my email id under "scope" section, any help on it would be appreciated ,Thanks!!.

**Comment by bpedroza** [comment]
This is something you will need to figure out with the server providing the response. Nothing to do with this package.
