### ISSUE TITLE
How can I get CSRF before exchangeForAccessToken?

### ISSUE THREAD

**Issue by ryanw3b3r** [bpedroza/js-pkce#28]
Hi,

It's not really an issue with js-pkce code, more like a question about implementation.

I'm using Laravel with Laravel Passport as my backend. `/oauth/token` is secured by CSRF token check, so when I do `exchangeForAccessToken` I need to send CSRF token with the request, otherwise it will be rejected. So the question is: how do I get CSRF token after I'm logged in and redirected back from backend's login screen to my frontend app? I think CSRF token is sent back in a cookie, so maybe I could re-use it, but then how do I access it? `document.cookie` is empty.

**Comment by bpedroza** [comment]
Sorry, but your question is out of the scope of this project. Maybe consult the laravel documentation.
