### ISSUE TITLE
Support for custom params

### ISSUE THREAD

**Issue by mvdobrinin** [bpedroza/js-pkce#3]
Would be good to be able to send custom query params on the calls to the auth server. Some servers like PingFederate support the concept of authorization adapters, which should be set by the OAuth client.

**Comment by bpedroza** [comment]
I would be open to this. Feel free to make a PR. If you can't do that, could you please provide an example of how you think this might look? For example - are you looking for an optional argument that can be passed to the `authorizeUrl` method? Maybe an array of custom parameters?

**Comment by bpedroza** [comment]
Could you please also provide a link to the documentation and any specifications for these authorization adapters? It might be worth while to have a different package for adapters if this is something others will need to use with different services.

**Comment by mvdobrinin** [comment]
Here is what other clients are doing in this regard - [just letting user configure whatever they want](https://github.com/BitySA/oauth2-auth-code-pkce#extra-parameters-which-other-oauth-servers-require).

For PingFederate sometimes you need to add the following query param to the authorize endpoint call.

```
&pfidpadapterid=OAuthAdapterCCDS
```

This is just an example of course, and there are different adapters that can be used.

**Comment by mvdobrinin** [comment]
You can see it in the docs here - https://docs.pingidentity.com/bundle/pingfederate-93/page/nfr1564003024683.html.

**Comment by bpedroza** [comment]
Thanks. I probably won't get to this over the holiday, but I will work on it soon.
