### ISSUE TITLE
id token

### ISSUE THREAD

**Issue by tommed** [bpedroza/js-pkce#30]
Some providers (including Azure AD) provide Access Tokens which aren't JWT and contain no information - this is perfectly acceptable as per the standard RFC. But I see no way using your library to acquire the ID token?

Can you provide a method for accessing the ID token? E.g., `exchangeForIDToken`?

Thanks,

**Comment by tommed** [comment]
Ah ok, the ID token is present, but missing from your TS interface:

```typescript
export default interface ITokenResponse {
    access_token: string;
    expires_in: number;
    refresh_expires_in: number;
    refresh_token: string;
    scope: string;
    token_type: string;
}
```

**Comment by bpedroza** [comment]
The interface should not stop you from getting any data from the actual response. Are you requesting a change here? Or did you get it figured out?

**Comment by tommed** [comment]
Figured it out.. probably just an FYI as the Interface is incomplete?
Up to you.

**Comment by bpedroza** [comment]
Great. At this time I am not going to add provider specific response details to the interface.
