### ISSUE TITLE
Not usable from browser extensions due to usage of Storage API

### ISSUE THREAD

**Issue by djahandarie** [bpedroza/js-pkce#32]
MV3 browser extensions only expose the StorageArea API (via chrome.storage.session for example), not the Storage API in service workers.

The StorageArea API is asynchronous so it is not possible to build a Storage API shim around it to pass into the js-pkce `storage` config variable either.

That means it's impossible to use this library from a Chrome extension currently.

1. Can you think of a workaround?
2. Would it be possible to support extensions / StorageArea directly?

**Comment by bpedroza** [comment]
I'm not familiar enough with what's available in a browser extension to give any recommendation. My only advice would be to either:
1. Try to build a wrapper that implements the Storage interface.
2. Fork this repo and change the code to support your needs.
