### ISSUE TITLE
Add configuration to allow sending credentials

### ISSUE THREAD

**Issue by bennovakovic** [bpedroza/js-pkce#35]
Currently the fetch POST request for a token sets `credentials` to `omit`. But this breaks when using PKCE across domains when the remote server has correctly configured Allow-Origins specified.

I have done some testing in the browser, and I can see the fetch fails because the remote server can't read the cookies it has created for that user during the authorization step. If you simply go into the console and right-click the failed request and select Copy -> Copy Fetch Request, and paste it into the console, and change `credentials` to `include` rather than `omit`, it works as expected.

Would you consider extending this library to allow correctly configured CORS implementaions? Thanks!

**Comment by bpedroza** [comment]
Yes. Can you please give me an example of the additional parameters you send for CORS? I would like to also update readme with some details.

**Comment by bpedroza** [comment]
This is good. No need to update the PR I'm planning to clean up the readme a bit anyways. Thanks.

**Comment by bpedroza** [comment]
After reviewing I would like some changes to this implementation. Please see PR.

**Comment by bpedroza** [comment]
New feature is now available in version 1.4.0
