### ISSUE TITLE
PKCE.exchangeForAccessToken and error response

### ISSUE THREAD

**Issue by superosku** [bpedroza/js-pkce#46]
The `PKCE.exchangeForAccessToken` method is typed to return `Promise<ITokenResponse>` where `ITokenResponse` is typed to be the following:

```
export default interface ITokenResponse {
    access_token: string;
    expires_in: number;
    refresh_expires_in: number;
    refresh_token: string;
    scope: string;
    token_type: string;
}
```

This is incorrect since the token endpoint can return error response as well: https://www.rfc-editor.org/rfc/rfc6749#section-5.2

Based on my testing it seems that the `PKCE.exchangeForAccessToken` function just returns the error response such as `{"error": "invalid_grant"}` which is not what the types suggest.

Suggestion:
Either make the function return union of these types or then throw an exception when an error is returned from the authentication server.

**Comment by bpedroza** [comment]
Yeah. I think making the return type either the token response or error object is a a good solution here. Throwing an exception would be a breaking change. Please feel free to make a PR with this update. If not, I will get to it eventually.

**Comment by bpedroza** [comment]
After reviewing the code, this issue is not valid. Errors call reject, currently throwing an exception. This behavior is exactly what your second suggestion is. This can be seen in the [test cases.](https://github.com/bpedroza/js-pkce/blob/12d14f097ade2ba027858e422761d64a36f98762/tests/PKCE.test.ts#L48)
