### ISSUE TITLE
Firefox sessionStorage Issues

### ISSUE THREAD

**Issue by bpedroza** [bpedroza/js-pkce#5]
Issue originates from PR - https://github.com/bpedroza/js-pkce/pull/4 from @revir

**My Findings:** 
I tested in firefox, and this is not the case. Are you doing something else with your flow? The sessionStorage data is not persisted across tabs, but it is persisted in the same tab. Are you opening a new window to authorize or something?

**Comment by revir** [comment]
Yes, I followed your guidelines to replace the location history to authorize. I use it in my project: https://github.com/pnlpal/dictionaries,  though it's a popup window type, but still it's a window. No new tab or new window. I also suspect it's a bug, my env is Firefox 82.0.2-1 on Manjaro Linux. 
I will have more test, and will tell you more what i find. Thank you.

**Comment by bpedroza** [comment]
Can you please give me a link to the part of the code that this library is being used?

**Comment by revir** [comment]
https://github.com/pnlpal/dictionaries/blob/master/src/content/music-player.coffee#L41-L72

It's in coffee script, kind of like python. 
when click on authorize, the function `authorize` will be called, so the flow begins.

**Comment by revir** [comment]
@bpedroza  oh no, my bad. I found the problem. I use it in an iframe, then change the location of the top window.

**Comment by bpedroza** [comment]
Thanks. I'll check it out. Please continue your own testing and let me know what you find.

**Comment by bpedroza** [comment]
Ah, that makes sense. Can you work around on your end?

**Comment by revir** [comment]
I guess that's why the sessionStorage is freed. Somehow chrome is not like that.

**Comment by revir** [comment]
yeah, it's should be my problem. Somehow this modular is not working on Firefox anyway...
Thanks for helping though, I guess this is a interesting way to debug.

**Comment by bpedroza** [comment]
Sure. If you're having more issues with firefox, please let me know. I want this package to work for all modern browsers, and if sessionStorage is going to continue to be a problem, maybe we can introduce a way to swap storage types.

**Comment by revir** [comment]
sure.
